package com.example.myapp;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JFrame;

/**
 *
 * @author Alya
 */
public class HalamanProduk extends javax.swing.JFrame {

    
    public HalamanProduk() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_navbar = new javax.swing.JPanel();
        panel_logo = new javax.swing.JPanel();
        label_logo = new javax.swing.JLabel();
        panel_home = new javax.swing.JPanel();
        label_home = new javax.swing.JLabel();
        panel_product = new javax.swing.JPanel();
        label_product = new javax.swing.JLabel();
        panel_bestSeller = new javax.swing.JPanel();
        label_bestSeller = new javax.swing.JLabel();
        panel_review = new javax.swing.JPanel();
        label_review = new javax.swing.JLabel();
        panel_about = new javax.swing.JPanel();
        label_about = new javax.swing.JLabel();
        panel_content = new javax.swing.JPanel();
        label_cimory = new javax.swing.JLabel();
        label_subHeader = new javax.swing.JLabel();
        label_subHeader2 = new javax.swing.JLabel();
        panel_frisian = new javax.swing.JPanel();
        frisian_foto = new javax.swing.JLabel();
        frisian_desc = new javax.swing.JLabel();
        frisian_button = new javax.swing.JButton();
        panel_indomilk = new javax.swing.JPanel();
        indomilk_foto = new javax.swing.JLabel();
        indomilk_desc = new javax.swing.JLabel();
        indomilk_button = new javax.swing.JButton();
        panel_ultra = new javax.swing.JPanel();
        ultra_foto = new javax.swing.JLabel();
        ultra_desc = new javax.swing.JLabel();
        ultra_button = new javax.swing.JButton();
        panel_cimory = new javax.swing.JPanel();
        cimory_foto = new javax.swing.JLabel();
        cimory_desc = new javax.swing.JLabel();
        cimory_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(234, 255, 255));
        setSize(new java.awt.Dimension(1920, 1080));

        panel_navbar.setBackground(new java.awt.Color(224, 240, 255));
        panel_navbar.setMaximumSize(null);
        panel_navbar.setPreferredSize(new java.awt.Dimension(725, 75));

        panel_logo.setBackground(new java.awt.Color(224, 240, 255));

        label_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-milkchamps.png"))); // NOI18N

        javax.swing.GroupLayout panel_logoLayout = new javax.swing.GroupLayout(panel_logo);
        panel_logo.setLayout(panel_logoLayout);
        panel_logoLayout.setHorizontalGroup(
            panel_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_logoLayout.setVerticalGroup(
            panel_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_home.setBackground(new java.awt.Color(224, 240, 255));
        panel_home.setPreferredSize(new java.awt.Dimension(90, 75));

        label_home.setBackground(new java.awt.Color(234, 255, 255));
        label_home.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_home.setText("Home");
        label_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_home.setFocusable(false);
        label_home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_homeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_homeLayout = new javax.swing.GroupLayout(panel_home);
        panel_home.setLayout(panel_homeLayout);
        panel_homeLayout.setHorizontalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_home, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panel_homeLayout.setVerticalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_home, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        panel_product.setBackground(new java.awt.Color(224, 240, 255));

        label_product.setBackground(new java.awt.Color(234, 255, 255));
        label_product.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_product.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_product.setText("Product");
        label_product.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_product.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_productLayout = new javax.swing.GroupLayout(panel_product);
        panel_product.setLayout(panel_productLayout);
        panel_productLayout.setHorizontalGroup(
            panel_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_productLayout.createSequentialGroup()
                .addComponent(label_product, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_productLayout.setVerticalGroup(
            panel_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_product, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        panel_bestSeller.setBackground(new java.awt.Color(224, 240, 255));

        label_bestSeller.setBackground(new java.awt.Color(234, 255, 255));
        label_bestSeller.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_bestSeller.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_bestSeller.setText("Best Seller");
        label_bestSeller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_bestSeller.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_bestSellerLayout = new javax.swing.GroupLayout(panel_bestSeller);
        panel_bestSeller.setLayout(panel_bestSellerLayout);
        panel_bestSellerLayout.setHorizontalGroup(
            panel_bestSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_bestSeller, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panel_bestSellerLayout.setVerticalGroup(
            panel_bestSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_bestSeller, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        panel_review.setBackground(new java.awt.Color(224, 240, 255));

        label_review.setBackground(new java.awt.Color(234, 255, 255));
        label_review.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_review.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_review.setText("Review");
        label_review.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_review.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_reviewLayout = new javax.swing.GroupLayout(panel_review);
        panel_review.setLayout(panel_reviewLayout);
        panel_reviewLayout.setHorizontalGroup(
            panel_reviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_review, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );
        panel_reviewLayout.setVerticalGroup(
            panel_reviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_review, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        panel_about.setBackground(new java.awt.Color(224, 240, 255));

        label_about.setBackground(new java.awt.Color(224, 240, 255));
        label_about.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_about.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_about.setText("About");
        label_about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_about.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_aboutLayout = new javax.swing.GroupLayout(panel_about);
        panel_about.setLayout(panel_aboutLayout);
        panel_aboutLayout.setHorizontalGroup(
            panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_about, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        panel_aboutLayout.setVerticalGroup(
            panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_about, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_navbarLayout = new javax.swing.GroupLayout(panel_navbar);
        panel_navbar.setLayout(panel_navbarLayout);
        panel_navbarLayout.setHorizontalGroup(
            panel_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navbarLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(panel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_bestSeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_review, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_about, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(947, Short.MAX_VALUE))
        );
        panel_navbarLayout.setVerticalGroup(
            panel_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navbarLayout.createSequentialGroup()
                .addGroup(panel_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_about, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_bestSeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_review, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel_navbar, java.awt.BorderLayout.PAGE_START);

        panel_content.setBackground(new java.awt.Color(224, 240, 255));

        label_cimory.setBackground(new java.awt.Color(0, 102, 102));
        label_cimory.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        label_cimory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_cimory.setText("MILKCHAMPS");
        label_cimory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        label_subHeader.setBackground(new java.awt.Color(224, 240, 255));
        label_subHeader.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_subHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_subHeader.setText("Kembalikan  nutrisimu dengan milkchamp");
        label_subHeader.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        label_subHeader2.setBackground(new java.awt.Color(224, 240, 255));
        label_subHeader2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_subHeader2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_subHeader2.setText("Kelezatan alami yang membawa keajaiban");
        label_subHeader2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        panel_frisian.setBackground(new java.awt.Color(85, 194, 253));
        panel_frisian.setPreferredSize(new java.awt.Dimension(225, 325));

        frisian_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        frisian_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo frisian flag resize.png"))); // NOI18N
        frisian_foto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        frisian_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        frisian_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        frisian_desc.setText("Frisian Flag");
        frisian_desc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        frisian_button.setBackground(new java.awt.Color(0, 0, 102));
        frisian_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        frisian_button.setForeground(new java.awt.Color(255, 255, 255));
        frisian_button.setText("Beli Produk");
        frisian_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        frisian_button.setBorderPainted(false);
        frisian_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        frisian_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frisian_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_frisianLayout = new javax.swing.GroupLayout(panel_frisian);
        panel_frisian.setLayout(panel_frisianLayout);
        panel_frisianLayout.setHorizontalGroup(
            panel_frisianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frisian_desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_frisianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frisian_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_frisianLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(frisian_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        panel_frisianLayout.setVerticalGroup(
            panel_frisianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_frisianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frisian_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(frisian_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(frisian_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        panel_indomilk.setBackground(new java.awt.Color(85, 194, 253));
        panel_indomilk.setPreferredSize(new java.awt.Dimension(225, 325));

        indomilk_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        indomilk_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-indomilk resize.png"))); // NOI18N
        indomilk_foto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        indomilk_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        indomilk_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        indomilk_desc.setText("IndoMilk");
        indomilk_desc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        indomilk_button.setBackground(new java.awt.Color(0, 0, 102));
        indomilk_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        indomilk_button.setForeground(new java.awt.Color(255, 255, 255));
        indomilk_button.setText("Beli Produk");
        indomilk_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        indomilk_button.setBorderPainted(false);
        indomilk_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        indomilk_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indomilk_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_indomilkLayout = new javax.swing.GroupLayout(panel_indomilk);
        panel_indomilk.setLayout(panel_indomilkLayout);
        panel_indomilkLayout.setHorizontalGroup(
            panel_indomilkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indomilk_desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_indomilkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(indomilk_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel_indomilkLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(indomilk_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_indomilkLayout.setVerticalGroup(
            panel_indomilkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_indomilkLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(indomilk_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(indomilk_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(indomilk_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        panel_ultra.setBackground(new java.awt.Color(85, 194, 253));
        panel_ultra.setPreferredSize(new java.awt.Dimension(225, 325));

        ultra_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ultra_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-ultrajaya resize.png"))); // NOI18N
        ultra_foto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ultra_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ultra_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ultra_desc.setText("UltraMilk");
        ultra_desc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ultra_button.setBackground(new java.awt.Color(0, 0, 102));
        ultra_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ultra_button.setForeground(new java.awt.Color(255, 255, 255));
        ultra_button.setText("Beli Produk");
        ultra_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        ultra_button.setBorderPainted(false);
        ultra_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ultra_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultra_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ultraLayout = new javax.swing.GroupLayout(panel_ultra);
        panel_ultra.setLayout(panel_ultraLayout);
        panel_ultraLayout.setHorizontalGroup(
            panel_ultraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ultra_desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_ultraLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(ultra_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(panel_ultraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ultra_foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_ultraLayout.setVerticalGroup(
            panel_ultraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ultraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ultra_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ultra_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ultra_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panel_cimory.setBackground(new java.awt.Color(85, 194, 253));
        panel_cimory.setPreferredSize(new java.awt.Dimension(225, 325));

        cimory_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cimory_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-cimory resize.png"))); // NOI18N
        cimory_foto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cimory_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cimory_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cimory_desc.setText("Cimory");
        cimory_desc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cimory_button.setBackground(new java.awt.Color(0, 0, 102));
        cimory_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cimory_button.setForeground(new java.awt.Color(255, 255, 255));
        cimory_button.setText("Beli Produk");
        cimory_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        cimory_button.setBorderPainted(false);
        cimory_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cimory_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cimory_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_cimoryLayout = new javax.swing.GroupLayout(panel_cimory);
        panel_cimory.setLayout(panel_cimoryLayout);
        panel_cimoryLayout.setHorizontalGroup(
            panel_cimoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cimory_desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_cimoryLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(cimory_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(panel_cimoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cimory_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_cimoryLayout.setVerticalGroup(
            panel_cimoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cimoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cimory_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(cimory_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cimory_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout panel_contentLayout = new javax.swing.GroupLayout(panel_content);
        panel_content.setLayout(panel_contentLayout);
        panel_contentLayout.setHorizontalGroup(
            panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contentLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(panel_frisian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(panel_indomilk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(panel_ultra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(panel_cimory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(panel_contentLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_cimory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_contentLayout.createSequentialGroup()
                        .addGap(558, 558, 558)
                        .addGroup(panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_subHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_subHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_contentLayout.setVerticalGroup(
            panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contentLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(label_cimory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(label_subHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_subHeader2)
                .addGap(127, 127, 127)
                .addGroup(panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_ultra, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addComponent(panel_cimory, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addComponent(panel_indomilk, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addComponent(panel_frisian, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        getContentPane().add(panel_content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1551, 912));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void label_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_homeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label_homeMouseClicked

    private void frisian_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frisian_buttonActionPerformed
        Produk_FrisianFlag frame = new Produk_FrisianFlag();
        frame.setVisible(true);
    }//GEN-LAST:event_frisian_buttonActionPerformed

    private void indomilk_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indomilk_buttonActionPerformed
        Produk_Indomilk frame = new Produk_Indomilk();
        frame.setVisible(true);
    }//GEN-LAST:event_indomilk_buttonActionPerformed

    private void ultra_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultra_buttonActionPerformed
        Produk_Ultramilk frame = new Produk_Ultramilk();
        frame.setVisible(true);
    }//GEN-LAST:event_ultra_buttonActionPerformed

    private void cimory_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cimory_buttonActionPerformed
        Produk_Cimory frame = new Produk_Cimory();
        frame.setVisible(true);
    }//GEN-LAST:event_cimory_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Produk_Cimory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Produk_Cimory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Produk_Cimory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Produk_Cimory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HalamanProduk().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cimory_button;
    private javax.swing.JLabel cimory_desc;
    private javax.swing.JLabel cimory_foto;
    private javax.swing.JButton frisian_button;
    private javax.swing.JLabel frisian_desc;
    private javax.swing.JLabel frisian_foto;
    private javax.swing.JButton indomilk_button;
    private javax.swing.JLabel indomilk_desc;
    private javax.swing.JLabel indomilk_foto;
    private javax.swing.JLabel label_about;
    private javax.swing.JLabel label_bestSeller;
    private javax.swing.JLabel label_cimory;
    private javax.swing.JLabel label_home;
    private javax.swing.JLabel label_logo;
    private javax.swing.JLabel label_product;
    private javax.swing.JLabel label_review;
    private javax.swing.JLabel label_subHeader;
    private javax.swing.JLabel label_subHeader2;
    private javax.swing.JPanel panel_about;
    private javax.swing.JPanel panel_bestSeller;
    private javax.swing.JPanel panel_cimory;
    private javax.swing.JPanel panel_content;
    private javax.swing.JPanel panel_frisian;
    private javax.swing.JPanel panel_home;
    private javax.swing.JPanel panel_indomilk;
    private javax.swing.JPanel panel_logo;
    private javax.swing.JPanel panel_navbar;
    private javax.swing.JPanel panel_product;
    private javax.swing.JPanel panel_review;
    private javax.swing.JPanel panel_ultra;
    private javax.swing.JButton ultra_button;
    private javax.swing.JLabel ultra_desc;
    private javax.swing.JLabel ultra_foto;
    // End of variables declaration//GEN-END:variables
}
