package com.example.myapp;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JFrame;

/**
 *
 * @author Alya
 */
public class Homepage extends javax.swing.JFrame {

    public Homepage() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_navbar = new javax.swing.JPanel();
        panel_logo = new javax.swing.JPanel();
        label_logo = new javax.swing.JLabel();
        panel_home = new javax.swing.JPanel();
        label_home = new javax.swing.JLabel();
        panel_product = new javax.swing.JPanel();
        label_product = new javax.swing.JLabel();
        panel_bestSeller = new javax.swing.JPanel();
        label_bestSeller = new javax.swing.JLabel();
        panel_review = new javax.swing.JPanel();
        label_review = new javax.swing.JLabel();
        panel_about = new javax.swing.JPanel();
        label_about = new javax.swing.JLabel();
        panel_content = new javax.swing.JPanel();
        label_milkchamps = new javax.swing.JLabel();
        panel_desc = new javax.swing.JPanel();
        label_desc1 = new javax.swing.JLabel();
        label_desc2 = new javax.swing.JLabel();
        label_desc3 = new javax.swing.JLabel();
        label_desc4 = new javax.swing.JLabel();
        label_desc5 = new javax.swing.JLabel();
        label_desc6 = new javax.swing.JLabel();
        label_desc7 = new javax.swing.JLabel();
        label_fotoSusu = new javax.swing.JLabel();
        panel_login = new javax.swing.JPanel();
        label_login = new javax.swing.JLabel();
        panel_signUp = new javax.swing.JPanel();
        label_signUp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(234, 255, 255));
        setSize(new java.awt.Dimension(1920, 1080));

        panel_navbar.setBackground(new java.awt.Color(224, 240, 255));
        panel_navbar.setMaximumSize(null);
        panel_navbar.setPreferredSize(new java.awt.Dimension(725, 75));

        panel_logo.setBackground(new java.awt.Color(224, 240, 255));

        label_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-milkchamps.png"))); // NOI18N

        javax.swing.GroupLayout panel_logoLayout = new javax.swing.GroupLayout(panel_logo);
        panel_logo.setLayout(panel_logoLayout);
        panel_logoLayout.setHorizontalGroup(
            panel_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_logoLayout.setVerticalGroup(
            panel_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_home.setBackground(new java.awt.Color(224, 240, 255));
        panel_home.setPreferredSize(new java.awt.Dimension(90, 75));

        label_home.setBackground(new java.awt.Color(234, 255, 255));
        label_home.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_home.setText("Home");
        label_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_home.setFocusable(false);
        label_home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_homeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_homeLayout = new javax.swing.GroupLayout(panel_home);
        panel_home.setLayout(panel_homeLayout);
        panel_homeLayout.setHorizontalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_home, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panel_homeLayout.setVerticalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_home, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel_product.setBackground(new java.awt.Color(224, 240, 255));

        label_product.setBackground(new java.awt.Color(234, 255, 255));
        label_product.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_product.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_product.setText("Product");
        label_product.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_product.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_productLayout = new javax.swing.GroupLayout(panel_product);
        panel_product.setLayout(panel_productLayout);
        panel_productLayout.setHorizontalGroup(
            panel_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_productLayout.createSequentialGroup()
                .addComponent(label_product, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_productLayout.setVerticalGroup(
            panel_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_product, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        panel_bestSeller.setBackground(new java.awt.Color(224, 240, 255));

        label_bestSeller.setBackground(new java.awt.Color(224, 240, 255));
        label_bestSeller.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_bestSeller.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_bestSeller.setText("Best Seller");
        label_bestSeller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_bestSeller.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_bestSellerLayout = new javax.swing.GroupLayout(panel_bestSeller);
        panel_bestSeller.setLayout(panel_bestSellerLayout);
        panel_bestSellerLayout.setHorizontalGroup(
            panel_bestSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_bestSeller, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panel_bestSellerLayout.setVerticalGroup(
            panel_bestSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_bestSeller, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        panel_review.setBackground(new java.awt.Color(224, 240, 255));

        label_review.setBackground(new java.awt.Color(224, 240, 255));
        label_review.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_review.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_review.setText("Review");
        label_review.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_review.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_reviewLayout = new javax.swing.GroupLayout(panel_review);
        panel_review.setLayout(panel_reviewLayout);
        panel_reviewLayout.setHorizontalGroup(
            panel_reviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_review, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );
        panel_reviewLayout.setVerticalGroup(
            panel_reviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_review, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        panel_about.setBackground(new java.awt.Color(224, 240, 255));

        label_about.setBackground(new java.awt.Color(224, 240, 255));
        label_about.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_about.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_about.setText("About");
        label_about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_about.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_aboutLayout = new javax.swing.GroupLayout(panel_about);
        panel_about.setLayout(panel_aboutLayout);
        panel_aboutLayout.setHorizontalGroup(
            panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_about, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        panel_aboutLayout.setVerticalGroup(
            panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_about, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_navbarLayout = new javax.swing.GroupLayout(panel_navbar);
        panel_navbar.setLayout(panel_navbarLayout);
        panel_navbarLayout.setHorizontalGroup(
            panel_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navbarLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(panel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_bestSeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_review, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_about, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(947, Short.MAX_VALUE))
        );
        panel_navbarLayout.setVerticalGroup(
            panel_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navbarLayout.createSequentialGroup()
                .addGroup(panel_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_about, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_bestSeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_review, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel_navbar, java.awt.BorderLayout.PAGE_START);

        panel_content.setBackground(new java.awt.Color(224, 240, 255));

        label_milkchamps.setBackground(new java.awt.Color(0, 102, 102));
        label_milkchamps.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        label_milkchamps.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_milkchamps.setText("MILKCHAMPS");
        label_milkchamps.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        panel_desc.setBackground(new java.awt.Color(224, 240, 255));

        label_desc1.setBackground(new java.awt.Color(234, 255, 255));
        label_desc1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_desc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_desc1.setText("Milkchamps adalah platform yang menyediakan produk");
        label_desc1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        label_desc2.setBackground(new java.awt.Color(234, 255, 255));
        label_desc2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_desc2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_desc2.setText("susu terbaik, termasuk Ultra Milk, Indomilk, dan Cimory.");
        label_desc2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_desc2.setPreferredSize(new java.awt.Dimension(454, 21));

        label_desc3.setBackground(new java.awt.Color(234, 255, 255));
        label_desc3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_desc3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_desc3.setText("Kami sangat merekomendasikan produk-produk ini");
        label_desc3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_desc3.setPreferredSize(new java.awt.Dimension(454, 21));

        label_desc4.setBackground(new java.awt.Color(234, 255, 255));
        label_desc4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_desc4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_desc4.setText("karena bahan-bahan berkualitas yang digunakan serta");
        label_desc4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_desc4.setPreferredSize(new java.awt.Dimension(454, 21));

        label_desc5.setBackground(new java.awt.Color(234, 255, 255));
        label_desc5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_desc5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_desc5.setText("rasa unik yang mereka tawarkan. Nikmati kelezatan dan");
        label_desc5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_desc5.setPreferredSize(new java.awt.Dimension(454, 21));

        label_desc6.setBackground(new java.awt.Color(234, 255, 255));
        label_desc6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_desc6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_desc6.setText("kualitas terbaik dari rangkaian produk susu yang kami ");
        label_desc6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_desc6.setPreferredSize(new java.awt.Dimension(454, 21));

        label_desc7.setBackground(new java.awt.Color(234, 255, 255));
        label_desc7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_desc7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_desc7.setText("tawarkan hanya di Milkchamps.");
        label_desc7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_desc7.setPreferredSize(new java.awt.Dimension(454, 21));

        javax.swing.GroupLayout panel_descLayout = new javax.swing.GroupLayout(panel_desc);
        panel_desc.setLayout(panel_descLayout);
        panel_descLayout.setHorizontalGroup(
            panel_descLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_desc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(label_desc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(label_desc3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(label_desc4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(label_desc5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(label_desc6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(label_desc7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_descLayout.setVerticalGroup(
            panel_descLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_descLayout.createSequentialGroup()
                .addComponent(label_desc1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_desc2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_desc3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_desc4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_desc5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_desc6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_desc7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        label_fotoSusu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_fotoSusu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gambar_susu_banyak-removebg-preview.png"))); // NOI18N
        label_fotoSusu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        panel_login.setBackground(new java.awt.Color(0, 0, 102));
        panel_login.setForeground(new java.awt.Color(255, 255, 255));

        label_login.setBackground(new java.awt.Color(0, 0, 102));
        label_login.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_login.setForeground(new java.awt.Color(255, 255, 255));
        label_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_login.setText("Login");
        label_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_loginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
        panel_login.setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_login, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_signUp.setBackground(new java.awt.Color(0, 0, 102));
        panel_signUp.setForeground(new java.awt.Color(255, 255, 255));

        label_signUp.setBackground(new java.awt.Color(0, 0, 102));
        label_signUp.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_signUp.setForeground(new java.awt.Color(255, 255, 255));
        label_signUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_signUp.setText("Sign Up");
        label_signUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_signUp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_signUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_signUpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_signUpLayout = new javax.swing.GroupLayout(panel_signUp);
        panel_signUp.setLayout(panel_signUpLayout);
        panel_signUpLayout.setHorizontalGroup(
            panel_signUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_signUp, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panel_signUpLayout.setVerticalGroup(
            panel_signUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_signUpLayout.createSequentialGroup()
                .addComponent(label_signUp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_contentLayout = new javax.swing.GroupLayout(panel_content);
        panel_content.setLayout(panel_contentLayout);
        panel_contentLayout.setHorizontalGroup(
            panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contentLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_contentLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(label_milkchamps, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addComponent(label_fotoSusu, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
            .addGroup(panel_contentLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(panel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(panel_signUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_contentLayout.setVerticalGroup(
            panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contentLayout.createSequentialGroup()
                .addGroup(panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_contentLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(label_milkchamps, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(panel_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_contentLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(label_fotoSusu, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_signUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(237, 237, 237))
        );

        getContentPane().add(panel_content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1551, 912));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void label_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_homeMouseClicked
        Homepage frame = new Homepage();
        frame.setVisible(true);
    }//GEN-LAST:event_label_homeMouseClicked

    private void label_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_loginMouseClicked
        Login frame = new Login();
        frame.setVisible(true);
    }//GEN-LAST:event_label_loginMouseClicked

    private void label_signUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_signUpMouseClicked
        SignUp frame = new SignUp();
        frame.setVisible(true);
    }//GEN-LAST:event_label_signUpMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Produk_Cimory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Produk_Cimory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Produk_Cimory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Produk_Cimory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Produk_Cimory().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_about;
    private javax.swing.JLabel label_bestSeller;
    private javax.swing.JLabel label_desc1;
    private javax.swing.JLabel label_desc2;
    private javax.swing.JLabel label_desc3;
    private javax.swing.JLabel label_desc4;
    private javax.swing.JLabel label_desc5;
    private javax.swing.JLabel label_desc6;
    private javax.swing.JLabel label_desc7;
    private javax.swing.JLabel label_fotoSusu;
    private javax.swing.JLabel label_home;
    private javax.swing.JLabel label_login;
    private javax.swing.JLabel label_logo;
    private javax.swing.JLabel label_milkchamps;
    private javax.swing.JLabel label_product;
    private javax.swing.JLabel label_review;
    private javax.swing.JLabel label_signUp;
    private javax.swing.JPanel panel_about;
    private javax.swing.JPanel panel_bestSeller;
    private javax.swing.JPanel panel_content;
    private javax.swing.JPanel panel_desc;
    private javax.swing.JPanel panel_home;
    private javax.swing.JPanel panel_login;
    private javax.swing.JPanel panel_logo;
    private javax.swing.JPanel panel_navbar;
    private javax.swing.JPanel panel_product;
    private javax.swing.JPanel panel_review;
    private javax.swing.JPanel panel_signUp;
    // End of variables declaration//GEN-END:variables
}
