package com.example.myapp;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Alya
 */
public class Produk_FrisianFlag extends javax.swing.JFrame {

    
    public Produk_FrisianFlag() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_navbar = new javax.swing.JPanel();
        panel_logo = new javax.swing.JPanel();
        label_logo = new javax.swing.JLabel();
        panel_home = new javax.swing.JPanel();
        label_home = new javax.swing.JLabel();
        panel_product = new javax.swing.JPanel();
        label_product = new javax.swing.JLabel();
        panel_bestSeller = new javax.swing.JPanel();
        label_bestSeller = new javax.swing.JLabel();
        panel_review = new javax.swing.JPanel();
        label_review = new javax.swing.JLabel();
        panel_about = new javax.swing.JPanel();
        label_about = new javax.swing.JLabel();
        panel_content = new javax.swing.JPanel();
        label_frisian = new javax.swing.JLabel();
        panel_cokelat = new javax.swing.JPanel();
        cokelat_foto = new javax.swing.JLabel();
        cokelat_desc = new javax.swing.JLabel();
        cokelat_button = new javax.swing.JButton();
        panel_coco = new javax.swing.JPanel();
        coco_foto = new javax.swing.JLabel();
        coco_desc = new javax.swing.JLabel();
        coco_button = new javax.swing.JButton();
        panel_ketan = new javax.swing.JPanel();
        ketan_foto = new javax.swing.JLabel();
        ketan_desc = new javax.swing.JLabel();
        ketan_button = new javax.swing.JButton();
        panel_low = new javax.swing.JPanel();
        low_foto = new javax.swing.JLabel();
        low_desc = new javax.swing.JLabel();
        low_button = new javax.swing.JButton();
        panel_back = new javax.swing.JPanel();
        label_back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(234, 255, 255));
        setSize(new java.awt.Dimension(1920, 1080));

        panel_navbar.setBackground(new java.awt.Color(224, 240, 255));
        panel_navbar.setMaximumSize(null);
        panel_navbar.setPreferredSize(new java.awt.Dimension(725, 75));

        panel_logo.setBackground(new java.awt.Color(224, 240, 255));

        label_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-milkchamps.png"))); // NOI18N

        javax.swing.GroupLayout panel_logoLayout = new javax.swing.GroupLayout(panel_logo);
        panel_logo.setLayout(panel_logoLayout);
        panel_logoLayout.setHorizontalGroup(
            panel_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panel_logoLayout.setVerticalGroup(
            panel_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_home.setBackground(new java.awt.Color(224, 240, 255));
        panel_home.setPreferredSize(new java.awt.Dimension(90, 75));

        label_home.setBackground(new java.awt.Color(234, 255, 255));
        label_home.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_home.setText("Home");
        label_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_home.setFocusable(false);
        label_home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_homeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_homeLayout = new javax.swing.GroupLayout(panel_home);
        panel_home.setLayout(panel_homeLayout);
        panel_homeLayout.setHorizontalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_home, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panel_homeLayout.setVerticalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_home, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel_product.setBackground(new java.awt.Color(224, 240, 255));

        label_product.setBackground(new java.awt.Color(234, 255, 255));
        label_product.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_product.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_product.setText("Product");
        label_product.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_product.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_productMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_productLayout = new javax.swing.GroupLayout(panel_product);
        panel_product.setLayout(panel_productLayout);
        panel_productLayout.setHorizontalGroup(
            panel_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_productLayout.createSequentialGroup()
                .addComponent(label_product, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_productLayout.setVerticalGroup(
            panel_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_product, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        panel_bestSeller.setBackground(new java.awt.Color(224, 240, 255));

        label_bestSeller.setBackground(new java.awt.Color(234, 255, 255));
        label_bestSeller.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_bestSeller.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_bestSeller.setText("Best Seller");
        label_bestSeller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_bestSeller.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_bestSellerLayout = new javax.swing.GroupLayout(panel_bestSeller);
        panel_bestSeller.setLayout(panel_bestSellerLayout);
        panel_bestSellerLayout.setHorizontalGroup(
            panel_bestSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_bestSeller, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panel_bestSellerLayout.setVerticalGroup(
            panel_bestSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_bestSeller, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        panel_review.setBackground(new java.awt.Color(224, 240, 255));

        label_review.setBackground(new java.awt.Color(234, 255, 255));
        label_review.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_review.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_review.setText("Review");
        label_review.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_review.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_reviewLayout = new javax.swing.GroupLayout(panel_review);
        panel_review.setLayout(panel_reviewLayout);
        panel_reviewLayout.setHorizontalGroup(
            panel_reviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_review, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );
        panel_reviewLayout.setVerticalGroup(
            panel_reviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_review, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        panel_about.setBackground(new java.awt.Color(224, 240, 255));

        label_about.setBackground(new java.awt.Color(234, 255, 255));
        label_about.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_about.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_about.setText("About");
        label_about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_about.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_aboutLayout = new javax.swing.GroupLayout(panel_about);
        panel_about.setLayout(panel_aboutLayout);
        panel_aboutLayout.setHorizontalGroup(
            panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_about, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        panel_aboutLayout.setVerticalGroup(
            panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_about, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_navbarLayout = new javax.swing.GroupLayout(panel_navbar);
        panel_navbar.setLayout(panel_navbarLayout);
        panel_navbarLayout.setHorizontalGroup(
            panel_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navbarLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(panel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_bestSeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_review, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_about, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(932, Short.MAX_VALUE))
        );
        panel_navbarLayout.setVerticalGroup(
            panel_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navbarLayout.createSequentialGroup()
                .addGroup(panel_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_about, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_bestSeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_review, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel_navbar, java.awt.BorderLayout.PAGE_START);

        panel_content.setBackground(new java.awt.Color(224, 240, 255));

        label_frisian.setBackground(new java.awt.Color(224, 240, 255));
        label_frisian.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        label_frisian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_frisian.setText("FRISIAN FLAG");
        label_frisian.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        panel_cokelat.setBackground(new java.awt.Color(85, 194, 253));
        panel_cokelat.setPreferredSize(new java.awt.Dimension(225, 325));

        cokelat_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cokelat_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frisian flag Cocolate.png"))); // NOI18N
        cokelat_foto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cokelat_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cokelat_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cokelat_desc.setText("Cokelat 225ml");
        cokelat_desc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cokelat_button.setBackground(new java.awt.Color(0, 0, 102));
        cokelat_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cokelat_button.setForeground(new java.awt.Color(255, 255, 255));
        cokelat_button.setText("Beli Produk");
        cokelat_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        cokelat_button.setBorderPainted(false);
        cokelat_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cokelat_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokelat_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_cokelatLayout = new javax.swing.GroupLayout(panel_cokelat);
        panel_cokelat.setLayout(panel_cokelatLayout);
        panel_cokelatLayout.setHorizontalGroup(
            panel_cokelatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cokelat_desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_cokelatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cokelat_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel_cokelatLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cokelat_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_cokelatLayout.setVerticalGroup(
            panel_cokelatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cokelatLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(cokelat_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cokelat_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cokelat_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panel_coco.setBackground(new java.awt.Color(85, 194, 253));
        panel_coco.setPreferredSize(new java.awt.Dimension(225, 325));

        coco_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coco_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frisian flag Coconut_Delight.png"))); // NOI18N
        coco_foto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        coco_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        coco_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coco_desc.setText("Coconut Delight 225ml");
        coco_desc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        coco_button.setBackground(new java.awt.Color(0, 0, 102));
        coco_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        coco_button.setForeground(new java.awt.Color(255, 255, 255));
        coco_button.setText("Beli Produk");
        coco_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        coco_button.setBorderPainted(false);
        coco_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        coco_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coco_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_cocoLayout = new javax.swing.GroupLayout(panel_coco);
        panel_coco.setLayout(panel_cocoLayout);
        panel_cocoLayout.setHorizontalGroup(
            panel_cocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coco_desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_cocoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(coco_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(panel_cocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_cocoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(coco_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel_cocoLayout.setVerticalGroup(
            panel_cocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cocoLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(coco_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(coco_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(panel_cocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_cocoLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(coco_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(130, Short.MAX_VALUE)))
        );

        panel_ketan.setBackground(new java.awt.Color(85, 194, 253));
        panel_ketan.setPreferredSize(new java.awt.Dimension(225, 325));

        ketan_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ketan_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frisian flag Ketan_Hitam.png"))); // NOI18N
        ketan_foto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ketan_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ketan_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ketan_desc.setText("Ketan Hitam 225ml");
        ketan_desc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ketan_button.setBackground(new java.awt.Color(0, 0, 102));
        ketan_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ketan_button.setForeground(new java.awt.Color(255, 255, 255));
        ketan_button.setText("Beli Produk");
        ketan_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        ketan_button.setBorderPainted(false);
        ketan_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ketan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketan_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ketanLayout = new javax.swing.GroupLayout(panel_ketan);
        panel_ketan.setLayout(panel_ketanLayout);
        panel_ketanLayout.setHorizontalGroup(
            panel_ketanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ketan_desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_ketanLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ketan_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(panel_ketanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_ketanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ketan_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel_ketanLayout.setVerticalGroup(
            panel_ketanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ketanLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(ketan_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ketan_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(panel_ketanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_ketanLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(ketan_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(130, Short.MAX_VALUE)))
        );

        panel_low.setBackground(new java.awt.Color(85, 194, 253));
        panel_low.setPreferredSize(new java.awt.Dimension(225, 325));

        low_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        low_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frisian flag vanilla.png"))); // NOI18N
        low_foto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        low_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        low_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        low_desc.setText("Low Fat Vanilla 225ml");
        low_desc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        low_button.setBackground(new java.awt.Color(0, 0, 102));
        low_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        low_button.setForeground(new java.awt.Color(255, 255, 255));
        low_button.setText("Beli Produk");
        low_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        low_button.setBorderPainted(false);
        low_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        low_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                low_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_lowLayout = new javax.swing.GroupLayout(panel_low);
        panel_low.setLayout(panel_lowLayout);
        panel_lowLayout.setHorizontalGroup(
            panel_lowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(low_desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_lowLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(low_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(panel_lowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_lowLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(low_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel_lowLayout.setVerticalGroup(
            panel_lowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_lowLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(low_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(low_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(panel_lowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_lowLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(low_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(130, Short.MAX_VALUE)))
        );

        panel_back.setBackground(new java.awt.Color(0, 0, 102));

        label_back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_back.setForeground(new java.awt.Color(255, 255, 255));
        label_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_back.setText("BACK");
        label_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_backLayout = new javax.swing.GroupLayout(panel_back);
        panel_back.setLayout(panel_backLayout);
        panel_backLayout.setHorizontalGroup(
            panel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_back, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panel_backLayout.setVerticalGroup(
            panel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_back, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_contentLayout = new javax.swing.GroupLayout(panel_content);
        panel_content.setLayout(panel_contentLayout);
        panel_contentLayout.setHorizontalGroup(
            panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_frisian, javax.swing.GroupLayout.DEFAULT_SIZE, 1537, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_contentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_cokelat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(panel_coco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(panel_ketan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(panel_low, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
            .addGroup(panel_contentLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panel_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_contentLayout.setVerticalGroup(
            panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contentLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(label_frisian, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179)
                .addGroup(panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_cokelat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_coco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_ketan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_low, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(panel_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(panel_content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1551, 912));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void label_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_homeMouseClicked
        HalamanProduk frame = new HalamanProduk();
        frame.setVisible(true);
    }//GEN-LAST:event_label_homeMouseClicked

    private void low_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_low_buttonActionPerformed
        JOptionPane.showMessageDialog(null, "Your Purchase is Being Processed");
    }//GEN-LAST:event_low_buttonActionPerformed

    private void ketan_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketan_buttonActionPerformed
        JOptionPane.showMessageDialog(null, "Your Purchase is Being Processed");
    }//GEN-LAST:event_ketan_buttonActionPerformed

    private void coco_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coco_buttonActionPerformed
        JOptionPane.showMessageDialog(null, "Your Purchase is Being Processed");
    }//GEN-LAST:event_coco_buttonActionPerformed

    private void cokelat_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokelat_buttonActionPerformed
        JOptionPane.showMessageDialog(null, "Your Purchase is Being Processed");
    }//GEN-LAST:event_cokelat_buttonActionPerformed

    private void label_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_productMouseClicked
        HalamanProduk frame = new HalamanProduk();
        frame.setVisible(true);
    }//GEN-LAST:event_label_productMouseClicked

    private void label_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_backMouseClicked
        HalamanProduk frame = new HalamanProduk();
        frame.setVisible(true);
    }//GEN-LAST:event_label_backMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Produk_FrisianFlag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Produk_FrisianFlag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Produk_FrisianFlag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Produk_FrisianFlag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Produk_FrisianFlag().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton coco_button;
    private javax.swing.JLabel coco_desc;
    private javax.swing.JLabel coco_foto;
    private javax.swing.JButton cokelat_button;
    private javax.swing.JLabel cokelat_desc;
    private javax.swing.JLabel cokelat_foto;
    private javax.swing.JButton ketan_button;
    private javax.swing.JLabel ketan_desc;
    private javax.swing.JLabel ketan_foto;
    private javax.swing.JLabel label_about;
    private javax.swing.JLabel label_back;
    private javax.swing.JLabel label_bestSeller;
    private javax.swing.JLabel label_frisian;
    private javax.swing.JLabel label_home;
    private javax.swing.JLabel label_logo;
    private javax.swing.JLabel label_product;
    private javax.swing.JLabel label_review;
    private javax.swing.JButton low_button;
    private javax.swing.JLabel low_desc;
    private javax.swing.JLabel low_foto;
    private javax.swing.JPanel panel_about;
    private javax.swing.JPanel panel_back;
    private javax.swing.JPanel panel_bestSeller;
    private javax.swing.JPanel panel_coco;
    private javax.swing.JPanel panel_cokelat;
    private javax.swing.JPanel panel_content;
    private javax.swing.JPanel panel_home;
    private javax.swing.JPanel panel_ketan;
    private javax.swing.JPanel panel_logo;
    private javax.swing.JPanel panel_low;
    private javax.swing.JPanel panel_navbar;
    private javax.swing.JPanel panel_product;
    private javax.swing.JPanel panel_review;
    // End of variables declaration//GEN-END:variables
}
