/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.myapp;
import javax.swing.JFrame;

/**
 *
 * @author Alya
 */
public class Login extends javax.swing.JFrame {

    
    public Login() {
        initComponents();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_base = new javax.swing.JPanel();
        label_milkchamps = new javax.swing.JLabel();
        panel_login = new javax.swing.JPanel();
        panel_email = new javax.swing.JPanel();
        label_email = new javax.swing.JLabel();
        label_inputEmail = new javax.swing.JTextField();
        panel_pass = new javax.swing.JPanel();
        label_pass = new javax.swing.JLabel();
        label_inputPass = new javax.swing.JPasswordField();
        panel_loginButton = new javax.swing.JPanel();
        label_loginButton = new javax.swing.JLabel();
        label_desc1 = new javax.swing.JLabel();
        label_desc2 = new javax.swing.JLabel();
        label_foto = new javax.swing.JLabel();
        panel_back = new javax.swing.JPanel();
        label_back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_base.setBackground(new java.awt.Color(224, 240, 255));
        panel_base.setPreferredSize(new java.awt.Dimension(1920, 1080));

        label_milkchamps.setBackground(new java.awt.Color(0, 102, 102));
        label_milkchamps.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        label_milkchamps.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_milkchamps.setText("MILKCHAMPS");
        label_milkchamps.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        panel_login.setBackground(new java.awt.Color(68, 174, 219));

        label_email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_email.setText("Email");

        label_inputEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_inputEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label_inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_inputEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_emailLayout = new javax.swing.GroupLayout(panel_email);
        panel_email.setLayout(panel_emailLayout);
        panel_emailLayout.setHorizontalGroup(
            panel_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_emailLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panel_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_email))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panel_emailLayout.setVerticalGroup(
            panel_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_emailLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(label_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        label_pass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_pass.setText("Password");

        label_inputPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_inputPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panel_passLayout = new javax.swing.GroupLayout(panel_pass);
        panel_pass.setLayout(panel_passLayout);
        panel_passLayout.setHorizontalGroup(
            panel_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_passLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panel_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_inputPass, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_pass))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_passLayout.setVerticalGroup(
            panel_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_passLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(label_pass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_inputPass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panel_loginButton.setBackground(new java.awt.Color(0, 0, 102));

        label_loginButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_loginButton.setForeground(new java.awt.Color(255, 255, 255));
        label_loginButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_loginButton.setText("LOGIN");
        label_loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_loginButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_loginButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_loginButtonLayout = new javax.swing.GroupLayout(panel_loginButton);
        panel_loginButton.setLayout(panel_loginButtonLayout);
        panel_loginButtonLayout.setHorizontalGroup(
            panel_loginButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );
        panel_loginButtonLayout.setVerticalGroup(
            panel_loginButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
        panel_login.setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panel_pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(panel_loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(panel_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(panel_loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        label_desc1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_desc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_desc1.setText("Kembalikan  nutrisimu dengan Milkchamps");
        label_desc1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        label_desc2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_desc2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_desc2.setText("Kelezatan alami yang membawa keajaiban");
        label_desc2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        label_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gambar_susu_banyak-removebg-preview.png"))); // NOI18N
        label_foto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        panel_back.setBackground(new java.awt.Color(68, 174, 219));

        label_back.setBackground(new java.awt.Color(68, 174, 219));
        label_back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_back.setForeground(new java.awt.Color(255, 255, 255));
        label_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_back.setText("BACK");
        label_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_backLayout = new javax.swing.GroupLayout(panel_back);
        panel_back.setLayout(panel_backLayout);
        panel_backLayout.setHorizontalGroup(
            panel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_back, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
        );
        panel_backLayout.setVerticalGroup(
            panel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_back, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_baseLayout = new javax.swing.GroupLayout(panel_base);
        panel_base.setLayout(panel_baseLayout);
        panel_baseLayout.setHorizontalGroup(
            panel_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_baseLayout.createSequentialGroup()
                .addGroup(panel_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_baseLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(panel_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_baseLayout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(panel_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_desc2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_desc1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel_baseLayout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(label_milkchamps))))
                            .addComponent(panel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(190, 190, 190)
                        .addComponent(label_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_baseLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(panel_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        panel_baseLayout.setVerticalGroup(
            panel_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_baseLayout.createSequentialGroup()
                .addGroup(panel_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_baseLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(label_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_baseLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(panel_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(label_milkchamps)
                        .addGap(27, 27, 27)
                        .addComponent(label_desc1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_desc2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(panel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(333, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_base, javax.swing.GroupLayout.PREFERRED_SIZE, 1609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 311, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_inputEmailActionPerformed

    private void label_loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_loginButtonMouseClicked
        HalamanProduk frame = new HalamanProduk();
        frame.setVisible(true);
    }//GEN-LAST:event_label_loginButtonMouseClicked

    private void label_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_backMouseClicked
        Homepage frame = new Homepage();
        frame.setVisible(true);
    }//GEN-LAST:event_label_backMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Login().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_back;
    private javax.swing.JLabel label_desc1;
    private javax.swing.JLabel label_desc2;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_foto;
    private javax.swing.JTextField label_inputEmail;
    private javax.swing.JPasswordField label_inputPass;
    private javax.swing.JLabel label_loginButton;
    private javax.swing.JLabel label_milkchamps;
    private javax.swing.JLabel label_pass;
    private javax.swing.JPanel panel_back;
    private javax.swing.JPanel panel_base;
    private javax.swing.JPanel panel_email;
    private javax.swing.JPanel panel_login;
    private javax.swing.JPanel panel_loginButton;
    private javax.swing.JPanel panel_pass;
    // End of variables declaration//GEN-END:variables
}
