package com.example.myapp;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Alya
 */
public class Produk_Indomilk extends javax.swing.JFrame {

    public Produk_Indomilk() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_navbar = new javax.swing.JPanel();
        panel_logo = new javax.swing.JPanel();
        label_logo = new javax.swing.JLabel();
        panel_home = new javax.swing.JPanel();
        label_home = new javax.swing.JLabel();
        panel_product = new javax.swing.JPanel();
        label_product = new javax.swing.JLabel();
        panel_bestSeller = new javax.swing.JPanel();
        label_bestSeller = new javax.swing.JLabel();
        panel_review = new javax.swing.JPanel();
        label_review = new javax.swing.JLabel();
        panel_about = new javax.swing.JPanel();
        label_about = new javax.swing.JLabel();
        panel_content = new javax.swing.JPanel();
        label_indomilk = new javax.swing.JLabel();
        panel_vanilla = new javax.swing.JPanel();
        vanilla_foto = new javax.swing.JLabel();
        vanilla_desc = new javax.swing.JLabel();
        vanilla_button = new javax.swing.JButton();
        panel_strawberry = new javax.swing.JPanel();
        strawberry_foto = new javax.swing.JLabel();
        strawberry_desc = new javax.swing.JLabel();
        strawberry_button = new javax.swing.JButton();
        panel_banana = new javax.swing.JPanel();
        banana_foto = new javax.swing.JLabel();
        banana_desc = new javax.swing.JLabel();
        banana_button = new javax.swing.JButton();
        panel_chocolate = new javax.swing.JPanel();
        chocolate_foto = new javax.swing.JLabel();
        chocolate_desc = new javax.swing.JLabel();
        chocolate_button = new javax.swing.JButton();
        panel_back = new javax.swing.JPanel();
        label_back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(234, 255, 255));
        setSize(new java.awt.Dimension(1920, 1080));

        panel_navbar.setBackground(new java.awt.Color(224, 240, 255));
        panel_navbar.setMaximumSize(null);
        panel_navbar.setPreferredSize(new java.awt.Dimension(725, 75));

        panel_logo.setBackground(new java.awt.Color(224, 240, 255));

        label_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-milkchamps.png"))); // NOI18N

        javax.swing.GroupLayout panel_logoLayout = new javax.swing.GroupLayout(panel_logo);
        panel_logo.setLayout(panel_logoLayout);
        panel_logoLayout.setHorizontalGroup(
            panel_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panel_logoLayout.setVerticalGroup(
            panel_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_home.setBackground(new java.awt.Color(224, 240, 255));
        panel_home.setPreferredSize(new java.awt.Dimension(90, 75));

        label_home.setBackground(new java.awt.Color(234, 255, 255));
        label_home.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_home.setText("Home");
        label_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_home.setFocusable(false);
        label_home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_homeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_homeLayout = new javax.swing.GroupLayout(panel_home);
        panel_home.setLayout(panel_homeLayout);
        panel_homeLayout.setHorizontalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_home, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panel_homeLayout.setVerticalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_home, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel_product.setBackground(new java.awt.Color(224, 240, 255));

        label_product.setBackground(new java.awt.Color(234, 255, 255));
        label_product.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_product.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_product.setText("Product");
        label_product.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_product.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_productMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_productLayout = new javax.swing.GroupLayout(panel_product);
        panel_product.setLayout(panel_productLayout);
        panel_productLayout.setHorizontalGroup(
            panel_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_productLayout.createSequentialGroup()
                .addComponent(label_product, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_productLayout.setVerticalGroup(
            panel_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_product, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        panel_bestSeller.setBackground(new java.awt.Color(224, 240, 255));

        label_bestSeller.setBackground(new java.awt.Color(234, 255, 255));
        label_bestSeller.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_bestSeller.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_bestSeller.setText("Best Seller");
        label_bestSeller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_bestSeller.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_bestSellerLayout = new javax.swing.GroupLayout(panel_bestSeller);
        panel_bestSeller.setLayout(panel_bestSellerLayout);
        panel_bestSellerLayout.setHorizontalGroup(
            panel_bestSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_bestSeller, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panel_bestSellerLayout.setVerticalGroup(
            panel_bestSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_bestSeller, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        panel_review.setBackground(new java.awt.Color(224, 240, 255));

        label_review.setBackground(new java.awt.Color(234, 255, 255));
        label_review.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_review.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_review.setText("Review");
        label_review.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_review.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_reviewLayout = new javax.swing.GroupLayout(panel_review);
        panel_review.setLayout(panel_reviewLayout);
        panel_reviewLayout.setHorizontalGroup(
            panel_reviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_review, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );
        panel_reviewLayout.setVerticalGroup(
            panel_reviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_review, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        panel_about.setBackground(new java.awt.Color(224, 240, 255));

        label_about.setBackground(new java.awt.Color(234, 255, 255));
        label_about.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_about.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_about.setText("About");
        label_about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_about.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_aboutLayout = new javax.swing.GroupLayout(panel_about);
        panel_about.setLayout(panel_aboutLayout);
        panel_aboutLayout.setHorizontalGroup(
            panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_about, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        panel_aboutLayout.setVerticalGroup(
            panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_about, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_navbarLayout = new javax.swing.GroupLayout(panel_navbar);
        panel_navbar.setLayout(panel_navbarLayout);
        panel_navbarLayout.setHorizontalGroup(
            panel_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navbarLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(panel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_bestSeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_review, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_about, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(932, Short.MAX_VALUE))
        );
        panel_navbarLayout.setVerticalGroup(
            panel_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navbarLayout.createSequentialGroup()
                .addGroup(panel_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_about, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_bestSeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_review, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel_navbar, java.awt.BorderLayout.PAGE_START);

        panel_content.setBackground(new java.awt.Color(224, 240, 255));

        label_indomilk.setBackground(new java.awt.Color(224, 240, 255));
        label_indomilk.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        label_indomilk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_indomilk.setText("INDOMILK");
        label_indomilk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        panel_vanilla.setBackground(new java.awt.Color(85, 194, 253));
        panel_vanilla.setPreferredSize(new java.awt.Dimension(225, 325));

        vanilla_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vanilla_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/indomilk_seoul_vanilla.png"))); // NOI18N
        vanilla_foto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        vanilla_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vanilla_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vanilla_desc.setText("Busan Vanilla 180ml");
        vanilla_desc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        vanilla_button.setBackground(new java.awt.Color(0, 0, 102));
        vanilla_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vanilla_button.setForeground(new java.awt.Color(255, 255, 255));
        vanilla_button.setText("Beli Produk");
        vanilla_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        vanilla_button.setBorderPainted(false);
        vanilla_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vanilla_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vanilla_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_vanillaLayout = new javax.swing.GroupLayout(panel_vanilla);
        panel_vanilla.setLayout(panel_vanillaLayout);
        panel_vanillaLayout.setHorizontalGroup(
            panel_vanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vanilla_desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_vanillaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vanilla_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel_vanillaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(vanilla_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_vanillaLayout.setVerticalGroup(
            panel_vanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_vanillaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(vanilla_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vanilla_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vanilla_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panel_strawberry.setBackground(new java.awt.Color(85, 194, 253));
        panel_strawberry.setPreferredSize(new java.awt.Dimension(225, 325));

        strawberry_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        strawberry_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/indomilk_strawberry.png"))); // NOI18N
        strawberry_foto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        strawberry_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        strawberry_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        strawberry_desc.setText("Korean Strawberry 180ml");
        strawberry_desc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        strawberry_button.setBackground(new java.awt.Color(0, 0, 102));
        strawberry_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        strawberry_button.setForeground(new java.awt.Color(255, 255, 255));
        strawberry_button.setText("Beli Produk");
        strawberry_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        strawberry_button.setBorderPainted(false);
        strawberry_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        strawberry_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawberry_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_strawberryLayout = new javax.swing.GroupLayout(panel_strawberry);
        panel_strawberry.setLayout(panel_strawberryLayout);
        panel_strawberryLayout.setHorizontalGroup(
            panel_strawberryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(strawberry_desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_strawberryLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(strawberry_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(panel_strawberryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_strawberryLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(strawberry_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel_strawberryLayout.setVerticalGroup(
            panel_strawberryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_strawberryLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(strawberry_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(strawberry_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(panel_strawberryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_strawberryLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(strawberry_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(130, Short.MAX_VALUE)))
        );

        panel_banana.setBackground(new java.awt.Color(85, 194, 253));
        panel_banana.setPreferredSize(new java.awt.Dimension(225, 325));

        banana_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        banana_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/indomilk_seoul_banana.png"))); // NOI18N
        banana_foto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        banana_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        banana_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        banana_desc.setText("Seoul Banana 180ml");
        banana_desc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        banana_button.setBackground(new java.awt.Color(0, 0, 102));
        banana_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        banana_button.setForeground(new java.awt.Color(255, 255, 255));
        banana_button.setText("Beli Produk");
        banana_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        banana_button.setBorderPainted(false);
        banana_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        banana_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banana_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_bananaLayout = new javax.swing.GroupLayout(panel_banana);
        panel_banana.setLayout(panel_bananaLayout);
        panel_bananaLayout.setHorizontalGroup(
            panel_bananaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(banana_desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_bananaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(banana_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(panel_bananaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_bananaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(banana_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel_bananaLayout.setVerticalGroup(
            panel_bananaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bananaLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(banana_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(banana_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(panel_bananaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_bananaLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(banana_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(130, Short.MAX_VALUE)))
        );

        panel_chocolate.setBackground(new java.awt.Color(85, 194, 253));
        panel_chocolate.setPreferredSize(new java.awt.Dimension(225, 325));

        chocolate_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chocolate_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/indomillk_korea_cholate.png"))); // NOI18N
        chocolate_foto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        chocolate_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chocolate_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chocolate_desc.setText("Jeju Chocolate 180ml");
        chocolate_desc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        chocolate_button.setBackground(new java.awt.Color(0, 0, 102));
        chocolate_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chocolate_button.setForeground(new java.awt.Color(255, 255, 255));
        chocolate_button.setText("Beli Produk");
        chocolate_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        chocolate_button.setBorderPainted(false);
        chocolate_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chocolate_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocolate_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_chocolateLayout = new javax.swing.GroupLayout(panel_chocolate);
        panel_chocolate.setLayout(panel_chocolateLayout);
        panel_chocolateLayout.setHorizontalGroup(
            panel_chocolateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chocolate_desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_chocolateLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(chocolate_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(panel_chocolateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_chocolateLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(chocolate_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel_chocolateLayout.setVerticalGroup(
            panel_chocolateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_chocolateLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(chocolate_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chocolate_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(panel_chocolateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_chocolateLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(chocolate_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(130, Short.MAX_VALUE)))
        );

        panel_back.setBackground(new java.awt.Color(0, 0, 102));

        label_back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_back.setForeground(new java.awt.Color(255, 255, 255));
        label_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_back.setText("BACK");
        label_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_backLayout = new javax.swing.GroupLayout(panel_back);
        panel_back.setLayout(panel_backLayout);
        panel_backLayout.setHorizontalGroup(
            panel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_back, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panel_backLayout.setVerticalGroup(
            panel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_back, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_contentLayout = new javax.swing.GroupLayout(panel_content);
        panel_content.setLayout(panel_contentLayout);
        panel_contentLayout.setHorizontalGroup(
            panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_indomilk, javax.swing.GroupLayout.DEFAULT_SIZE, 1537, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_contentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_vanilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(panel_strawberry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(panel_banana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(panel_chocolate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
            .addGroup(panel_contentLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panel_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_contentLayout.setVerticalGroup(
            panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contentLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(label_indomilk, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179)
                .addGroup(panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_vanilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_strawberry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_banana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_chocolate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(panel_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(panel_content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1551, 912));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void label_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_homeMouseClicked
        HalamanProduk frame = new HalamanProduk();
        frame.setVisible(true);
    }//GEN-LAST:event_label_homeMouseClicked

    private void chocolate_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocolate_buttonActionPerformed
        JOptionPane.showMessageDialog(null, "Your Purchase is Being Processed");
    }//GEN-LAST:event_chocolate_buttonActionPerformed

    private void banana_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banana_buttonActionPerformed
        JOptionPane.showMessageDialog(null, "Your Purchase is Being Processed");
    }//GEN-LAST:event_banana_buttonActionPerformed

    private void strawberry_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawberry_buttonActionPerformed
        JOptionPane.showMessageDialog(null, "Your Purchase is Being Processed");
    }//GEN-LAST:event_strawberry_buttonActionPerformed

    private void vanilla_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vanilla_buttonActionPerformed
        JOptionPane.showMessageDialog(null, "Your Purchase is Being Processed");
    }//GEN-LAST:event_vanilla_buttonActionPerformed

    private void label_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_productMouseClicked
        HalamanProduk frame = new HalamanProduk();
        frame.setVisible(true);
    }//GEN-LAST:event_label_productMouseClicked

    private void label_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_backMouseClicked
        HalamanProduk frame = new HalamanProduk();
        frame.setVisible(true);
    }//GEN-LAST:event_label_backMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Produk_Indomilk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Produk_Indomilk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Produk_Indomilk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Produk_Indomilk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Produk_Indomilk().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton banana_button;
    private javax.swing.JLabel banana_desc;
    private javax.swing.JLabel banana_foto;
    private javax.swing.JButton chocolate_button;
    private javax.swing.JLabel chocolate_desc;
    private javax.swing.JLabel chocolate_foto;
    private javax.swing.JLabel label_about;
    private javax.swing.JLabel label_back;
    private javax.swing.JLabel label_bestSeller;
    private javax.swing.JLabel label_home;
    private javax.swing.JLabel label_indomilk;
    private javax.swing.JLabel label_logo;
    private javax.swing.JLabel label_product;
    private javax.swing.JLabel label_review;
    private javax.swing.JPanel panel_about;
    private javax.swing.JPanel panel_back;
    private javax.swing.JPanel panel_banana;
    private javax.swing.JPanel panel_bestSeller;
    private javax.swing.JPanel panel_chocolate;
    private javax.swing.JPanel panel_content;
    private javax.swing.JPanel panel_home;
    private javax.swing.JPanel panel_logo;
    private javax.swing.JPanel panel_navbar;
    private javax.swing.JPanel panel_product;
    private javax.swing.JPanel panel_review;
    private javax.swing.JPanel panel_strawberry;
    private javax.swing.JPanel panel_vanilla;
    private javax.swing.JButton strawberry_button;
    private javax.swing.JLabel strawberry_desc;
    private javax.swing.JLabel strawberry_foto;
    private javax.swing.JButton vanilla_button;
    private javax.swing.JLabel vanilla_desc;
    private javax.swing.JLabel vanilla_foto;
    // End of variables declaration//GEN-END:variables
}
