package com.example.myapp;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Alya
 */
public class Produk_Ultramilk extends javax.swing.JFrame {

    
    public Produk_Ultramilk() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_navbar = new javax.swing.JPanel();
        panel_logo = new javax.swing.JPanel();
        label_logo = new javax.swing.JLabel();
        panel_home = new javax.swing.JPanel();
        label_home = new javax.swing.JLabel();
        panel_product = new javax.swing.JPanel();
        label_product = new javax.swing.JLabel();
        panel_bestSeller = new javax.swing.JPanel();
        label_bestSeller = new javax.swing.JLabel();
        panel_review = new javax.swing.JPanel();
        label_review = new javax.swing.JLabel();
        panel_about = new javax.swing.JPanel();
        label_about = new javax.swing.JLabel();
        panel_content = new javax.swing.JPanel();
        label_ultra = new javax.swing.JLabel();
        panel_fullCream = new javax.swing.JPanel();
        fullCream_foto = new javax.swing.JLabel();
        fullCream_desc = new javax.swing.JLabel();
        fullCream_button = new javax.swing.JButton();
        panel_cokelat = new javax.swing.JPanel();
        cokelat_foto = new javax.swing.JLabel();
        cokelat_desc = new javax.swing.JLabel();
        cokelat_button = new javax.swing.JButton();
        panel_lowFat = new javax.swing.JPanel();
        lowFat_foto = new javax.swing.JLabel();
        lowFat_desc = new javax.swing.JLabel();
        lowFat_button = new javax.swing.JButton();
        panel_stroberi = new javax.swing.JPanel();
        stroberi_foto = new javax.swing.JLabel();
        stroberi_desc = new javax.swing.JLabel();
        stroberi_button = new javax.swing.JButton();
        panel_taro = new javax.swing.JPanel();
        taro_foto = new javax.swing.JLabel();
        taro_desc = new javax.swing.JLabel();
        taro_button = new javax.swing.JButton();
        panel_back = new javax.swing.JPanel();
        label_back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(234, 255, 255));
        setSize(new java.awt.Dimension(1920, 1080));

        panel_navbar.setBackground(new java.awt.Color(224, 240, 255));
        panel_navbar.setMaximumSize(null);
        panel_navbar.setPreferredSize(new java.awt.Dimension(725, 75));

        panel_logo.setBackground(new java.awt.Color(224, 240, 255));

        label_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-milkchamps.png"))); // NOI18N

        javax.swing.GroupLayout panel_logoLayout = new javax.swing.GroupLayout(panel_logo);
        panel_logo.setLayout(panel_logoLayout);
        panel_logoLayout.setHorizontalGroup(
            panel_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panel_logoLayout.setVerticalGroup(
            panel_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_home.setBackground(new java.awt.Color(224, 240, 255));
        panel_home.setPreferredSize(new java.awt.Dimension(90, 75));

        label_home.setBackground(new java.awt.Color(234, 255, 255));
        label_home.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_home.setText("Home");
        label_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_home.setFocusable(false);
        label_home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_homeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_homeLayout = new javax.swing.GroupLayout(panel_home);
        panel_home.setLayout(panel_homeLayout);
        panel_homeLayout.setHorizontalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_home, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panel_homeLayout.setVerticalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_home, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel_product.setBackground(new java.awt.Color(224, 240, 255));

        label_product.setBackground(new java.awt.Color(234, 255, 255));
        label_product.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_product.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_product.setText("Product");
        label_product.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_product.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_productMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_productLayout = new javax.swing.GroupLayout(panel_product);
        panel_product.setLayout(panel_productLayout);
        panel_productLayout.setHorizontalGroup(
            panel_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_productLayout.createSequentialGroup()
                .addComponent(label_product, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_productLayout.setVerticalGroup(
            panel_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_product, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        panel_bestSeller.setBackground(new java.awt.Color(224, 240, 255));

        label_bestSeller.setBackground(new java.awt.Color(234, 255, 255));
        label_bestSeller.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_bestSeller.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_bestSeller.setText("Best Seller");
        label_bestSeller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_bestSeller.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_bestSellerLayout = new javax.swing.GroupLayout(panel_bestSeller);
        panel_bestSeller.setLayout(panel_bestSellerLayout);
        panel_bestSellerLayout.setHorizontalGroup(
            panel_bestSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_bestSeller, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panel_bestSellerLayout.setVerticalGroup(
            panel_bestSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_bestSeller, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        panel_review.setBackground(new java.awt.Color(224, 240, 255));

        label_review.setBackground(new java.awt.Color(234, 255, 255));
        label_review.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_review.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_review.setText("Review");
        label_review.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_review.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_reviewLayout = new javax.swing.GroupLayout(panel_review);
        panel_review.setLayout(panel_reviewLayout);
        panel_reviewLayout.setHorizontalGroup(
            panel_reviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_review, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );
        panel_reviewLayout.setVerticalGroup(
            panel_reviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_review, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        panel_about.setBackground(new java.awt.Color(224, 240, 255));

        label_about.setBackground(new java.awt.Color(234, 255, 255));
        label_about.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_about.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_about.setText("About");
        label_about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_about.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_aboutLayout = new javax.swing.GroupLayout(panel_about);
        panel_about.setLayout(panel_aboutLayout);
        panel_aboutLayout.setHorizontalGroup(
            panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_about, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        panel_aboutLayout.setVerticalGroup(
            panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_about, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_navbarLayout = new javax.swing.GroupLayout(panel_navbar);
        panel_navbar.setLayout(panel_navbarLayout);
        panel_navbarLayout.setHorizontalGroup(
            panel_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navbarLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(panel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_bestSeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_review, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_about, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(932, Short.MAX_VALUE))
        );
        panel_navbarLayout.setVerticalGroup(
            panel_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navbarLayout.createSequentialGroup()
                .addGroup(panel_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_about, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_bestSeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_review, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel_navbar, java.awt.BorderLayout.PAGE_START);

        panel_content.setBackground(new java.awt.Color(224, 240, 255));

        label_ultra.setBackground(new java.awt.Color(224, 240, 255));
        label_ultra.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        label_ultra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_ultra.setText("ULTRAMILK");
        label_ultra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        panel_fullCream.setBackground(new java.awt.Color(85, 194, 253));
        panel_fullCream.setPreferredSize(new java.awt.Dimension(225, 325));

        fullCream_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullCream_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ultramilk vanilla.png"))); // NOI18N
        fullCream_foto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        fullCream_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fullCream_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullCream_desc.setText("Full Cream 200ml");
        fullCream_desc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        fullCream_button.setBackground(new java.awt.Color(0, 0, 102));
        fullCream_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fullCream_button.setForeground(new java.awt.Color(255, 255, 255));
        fullCream_button.setText("Beli Produk");
        fullCream_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        fullCream_button.setBorderPainted(false);
        fullCream_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fullCream_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullCream_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_fullCreamLayout = new javax.swing.GroupLayout(panel_fullCream);
        panel_fullCream.setLayout(panel_fullCreamLayout);
        panel_fullCreamLayout.setHorizontalGroup(
            panel_fullCreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fullCream_desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_fullCreamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fullCream_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel_fullCreamLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(fullCream_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_fullCreamLayout.setVerticalGroup(
            panel_fullCreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fullCreamLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(fullCream_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fullCream_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fullCream_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panel_cokelat.setBackground(new java.awt.Color(85, 194, 253));
        panel_cokelat.setPreferredSize(new java.awt.Dimension(225, 325));

        cokelat_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cokelat_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ultramilk coklat.png"))); // NOI18N
        cokelat_foto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cokelat_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cokelat_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cokelat_desc.setText("Cokelat 200ml");
        cokelat_desc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cokelat_button.setBackground(new java.awt.Color(0, 0, 102));
        cokelat_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cokelat_button.setForeground(new java.awt.Color(255, 255, 255));
        cokelat_button.setText("Beli Produk");
        cokelat_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        cokelat_button.setBorderPainted(false);
        cokelat_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cokelat_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokelat_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_cokelatLayout = new javax.swing.GroupLayout(panel_cokelat);
        panel_cokelat.setLayout(panel_cokelatLayout);
        panel_cokelatLayout.setHorizontalGroup(
            panel_cokelatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cokelat_desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_cokelatLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(cokelat_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(panel_cokelatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_cokelatLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cokelat_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel_cokelatLayout.setVerticalGroup(
            panel_cokelatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cokelatLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(cokelat_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cokelat_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(panel_cokelatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_cokelatLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(cokelat_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(130, Short.MAX_VALUE)))
        );

        panel_lowFat.setBackground(new java.awt.Color(85, 194, 253));
        panel_lowFat.setPreferredSize(new java.awt.Dimension(225, 325));

        lowFat_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lowFat_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ultramilk coklat low fat.png"))); // NOI18N
        lowFat_foto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lowFat_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lowFat_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lowFat_desc.setText("Low Fat Chocolate 200ml");
        lowFat_desc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lowFat_button.setBackground(new java.awt.Color(0, 0, 102));
        lowFat_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lowFat_button.setForeground(new java.awt.Color(255, 255, 255));
        lowFat_button.setText("Beli Produk");
        lowFat_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        lowFat_button.setBorderPainted(false);
        lowFat_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lowFat_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowFat_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_lowFatLayout = new javax.swing.GroupLayout(panel_lowFat);
        panel_lowFat.setLayout(panel_lowFatLayout);
        panel_lowFatLayout.setHorizontalGroup(
            panel_lowFatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lowFat_desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_lowFatLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lowFat_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(panel_lowFatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_lowFatLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lowFat_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel_lowFatLayout.setVerticalGroup(
            panel_lowFatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_lowFatLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(lowFat_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lowFat_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(panel_lowFatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_lowFatLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lowFat_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(130, Short.MAX_VALUE)))
        );

        panel_stroberi.setBackground(new java.awt.Color(85, 194, 253));
        panel_stroberi.setPreferredSize(new java.awt.Dimension(225, 325));

        stroberi_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stroberi_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ultramilk strawberry.png"))); // NOI18N
        stroberi_foto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        stroberi_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        stroberi_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stroberi_desc.setText("Stroberi 200ml");
        stroberi_desc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        stroberi_button.setBackground(new java.awt.Color(0, 0, 102));
        stroberi_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stroberi_button.setForeground(new java.awt.Color(255, 255, 255));
        stroberi_button.setText("Beli Produk");
        stroberi_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        stroberi_button.setBorderPainted(false);
        stroberi_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stroberi_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stroberi_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_stroberiLayout = new javax.swing.GroupLayout(panel_stroberi);
        panel_stroberi.setLayout(panel_stroberiLayout);
        panel_stroberiLayout.setHorizontalGroup(
            panel_stroberiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stroberi_desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_stroberiLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(stroberi_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(panel_stroberiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_stroberiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(stroberi_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel_stroberiLayout.setVerticalGroup(
            panel_stroberiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_stroberiLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(stroberi_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stroberi_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(panel_stroberiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_stroberiLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(stroberi_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(130, Short.MAX_VALUE)))
        );

        panel_taro.setBackground(new java.awt.Color(85, 194, 253));
        panel_taro.setPreferredSize(new java.awt.Dimension(225, 325));

        taro_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        taro_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ultramilk taro.png"))); // NOI18N
        taro_foto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        taro_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taro_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        taro_desc.setText("Taro 200ml");
        taro_desc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        taro_button.setBackground(new java.awt.Color(0, 0, 102));
        taro_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        taro_button.setForeground(new java.awt.Color(255, 255, 255));
        taro_button.setText("Beli Produk");
        taro_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        taro_button.setBorderPainted(false);
        taro_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        taro_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taro_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_taroLayout = new javax.swing.GroupLayout(panel_taro);
        panel_taro.setLayout(panel_taroLayout);
        panel_taroLayout.setHorizontalGroup(
            panel_taroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taro_desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_taroLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(taro_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(panel_taroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_taroLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(taro_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel_taroLayout.setVerticalGroup(
            panel_taroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_taroLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(taro_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(taro_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(panel_taroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_taroLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(taro_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(130, Short.MAX_VALUE)))
        );

        panel_back.setBackground(new java.awt.Color(0, 0, 102));

        label_back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_back.setForeground(new java.awt.Color(255, 255, 255));
        label_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_back.setText("BACK");
        label_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_backLayout = new javax.swing.GroupLayout(panel_back);
        panel_back.setLayout(panel_backLayout);
        panel_backLayout.setHorizontalGroup(
            panel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_back, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panel_backLayout.setVerticalGroup(
            panel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_back, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_contentLayout = new javax.swing.GroupLayout(panel_content);
        panel_content.setLayout(panel_contentLayout);
        panel_contentLayout.setHorizontalGroup(
            panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_ultra, javax.swing.GroupLayout.DEFAULT_SIZE, 1537, Short.MAX_VALUE)
            .addGroup(panel_contentLayout.createSequentialGroup()
                .addGroup(panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_contentLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(panel_fullCream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(panel_cokelat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(panel_lowFat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(panel_stroberi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(panel_taro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_contentLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(panel_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_contentLayout.setVerticalGroup(
            panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contentLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(label_ultra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181)
                .addGroup(panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_fullCream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_cokelat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_lowFat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_stroberi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_taro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(panel_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(panel_content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1551, 912));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void label_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_homeMouseClicked
        HalamanProduk frame = new HalamanProduk();
        frame.setVisible(true);
    }//GEN-LAST:event_label_homeMouseClicked

    private void stroberi_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stroberi_buttonActionPerformed
        JOptionPane.showMessageDialog(null, "Your Purchase is Being Processed");
    }//GEN-LAST:event_stroberi_buttonActionPerformed

    private void lowFat_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowFat_buttonActionPerformed
        JOptionPane.showMessageDialog(null, "Your Purchase is Being Processed");
    }//GEN-LAST:event_lowFat_buttonActionPerformed

    private void cokelat_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokelat_buttonActionPerformed
        JOptionPane.showMessageDialog(null, "Your Purchase is Being Processed");
    }//GEN-LAST:event_cokelat_buttonActionPerformed

    private void fullCream_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullCream_buttonActionPerformed
        JOptionPane.showMessageDialog(null, "Your Purchase is Being Processed");
    }//GEN-LAST:event_fullCream_buttonActionPerformed

    private void taro_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taro_buttonActionPerformed
        JOptionPane.showMessageDialog(null, "Your Purchase is Being Processed");
    }//GEN-LAST:event_taro_buttonActionPerformed

    private void label_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_productMouseClicked
        HalamanProduk frame = new HalamanProduk();
        frame.setVisible(true);
    }//GEN-LAST:event_label_productMouseClicked

    private void label_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_backMouseClicked
        HalamanProduk frame = new HalamanProduk();
        frame.setVisible(true);
    }//GEN-LAST:event_label_backMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Produk_Ultramilk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Produk_Ultramilk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Produk_Ultramilk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Produk_Ultramilk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Produk_Ultramilk().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cokelat_button;
    private javax.swing.JLabel cokelat_desc;
    private javax.swing.JLabel cokelat_foto;
    private javax.swing.JButton fullCream_button;
    private javax.swing.JLabel fullCream_desc;
    private javax.swing.JLabel fullCream_foto;
    private javax.swing.JLabel label_about;
    private javax.swing.JLabel label_back;
    private javax.swing.JLabel label_bestSeller;
    private javax.swing.JLabel label_home;
    private javax.swing.JLabel label_logo;
    private javax.swing.JLabel label_product;
    private javax.swing.JLabel label_review;
    private javax.swing.JLabel label_ultra;
    private javax.swing.JButton lowFat_button;
    private javax.swing.JLabel lowFat_desc;
    private javax.swing.JLabel lowFat_foto;
    private javax.swing.JPanel panel_about;
    private javax.swing.JPanel panel_back;
    private javax.swing.JPanel panel_bestSeller;
    private javax.swing.JPanel panel_cokelat;
    private javax.swing.JPanel panel_content;
    private javax.swing.JPanel panel_fullCream;
    private javax.swing.JPanel panel_home;
    private javax.swing.JPanel panel_logo;
    private javax.swing.JPanel panel_lowFat;
    private javax.swing.JPanel panel_navbar;
    private javax.swing.JPanel panel_product;
    private javax.swing.JPanel panel_review;
    private javax.swing.JPanel panel_stroberi;
    private javax.swing.JPanel panel_taro;
    private javax.swing.JButton stroberi_button;
    private javax.swing.JLabel stroberi_desc;
    private javax.swing.JLabel stroberi_foto;
    private javax.swing.JButton taro_button;
    private javax.swing.JLabel taro_desc;
    private javax.swing.JLabel taro_foto;
    // End of variables declaration//GEN-END:variables
}
